version: "3.1"

services:
  dbtest:
    image: postgres:16.1
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
    volumes:
      - ./db_scripts/init/:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql

volumes:
  pg_data_test: {}
